apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-app-prod

bases:
- ../../base

patchesStrategicMerge:
  - ingress-prod.yaml
  - todo-backend-prod.yaml
  - todo-frontend-prod.yaml
