apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-app-prod

resources:
- ../../base
- ingress-prod.yaml

patches:
  - path: todo-backend-prod.yaml
  - path: todo-frontend-prod.yaml
