apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kustomize-
resources:
- postgres-deployment.yaml
- postgres-svc.yaml
- reddis-deployment.yaml
- reddis-svc.yaml
- todo-backend-deployment.yaml
- todo-backend-svc.yaml
- todo-frontend-deployment.yaml
- todo-frontend-svc.yaml
