apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: todo-
namespace: todo-app
resources:
- postgres-deployment.yaml
- postgres-svc.yaml
- redis-deployment.yaml
- redis-svc.yaml
- todo-backend-deployment.yaml
- todo-backend-svc.yaml
- todo-backend-seed.yaml
- todo-frontend-deployment.yaml
- todo-frontend-svc.yaml
- ingress.yaml
