apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - image: ghcr.io/chrishrb/ghcr.io/chrishrb/todo-frontend:main-1f93296
        name: todo-frontend
        ports:
        - containerPort: 80
