---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: init-wait
        image: busybox:latest
        command: ['sh', '-c', 'until nc -vz todo-postgres 5432 ; do sleep 1; done;']
      - name: init-migrate
        image: ghcr.io/chrishrb/ghcr.io/chrishrb/todo-backend:main-0d949ab
        command: ['/bin/sh', '/app/migrate.sh']
        env:
          - name: DATABASE_URL
            value: postgresql://admin:password@todo-postgres:5432/todo?schema=public
          - name: ADMIN_PASSWORD
            value: admin
          - name: USER_PASSWORD
            value: user
      containers:
      - image: ghcr.io/chrishrb/ghcr.io/chrishrb/todo-backend:main-0d949ab
        name: backend
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            value: postgresql://admin:password@todo-postgres:5432/todo?schema=public
          - name: AUTH_SECRET_KEY
            value: MYSECRETKEY
          - name: REDIS_CLIENT_URL
            value: redis://:password@todo-redis:6379
